name: camera_resolution
description: "Camera Resolution"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  json_serializable:

flutter:
  plugin:
    platforms:
      android:
        package: com.mobsolutions.camera_resolution.camera_resolution
        pluginClass: CameraResolutionPlugin
      ios:
        pluginClass: CameraResolutionPlugin
